export let dataFlatlist1 = [
  {
    name: 'CatFood',
    quantity: 1,
    price: '$ 60',
    id:1,
    url : require('../assets/productImages/firstListImages/image7.jpg'),
    smallDetail: 'Lorem ipsum is simply dummy text.',
    age:2,
    sex:'female',
    color:'White',
    owner:'Jennifer Lorence',
    distance:'2.56 km',
    bigDetail:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
  },
  {
    name: 'DoberMan Pup',
    quantity: 1,
    price: '$40',
    id:2,
    url : require('../assets/productImages/firstListImages/image.3.jpg'),
    smallDetail: 'Lorem ipsum is simply dummy text.',
    age:2,
    sex:'female',
    color:'White',
    owner:'Jennifer Lorence',
    distance:'2.56 km',
    bigDetail:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
 

  },
  {
    name: 'Leash',
    quantity: 1,
    price: '$40',
    id:3,
    url : require('../assets/productImages/firstListImages/image1.webp'),
    smallDetail: 'Lorem ipsum is simply dummy text.',
    age:2,
    sex:'female',
    color:'White',
    owner:'Jennifer Lorence',
    distance:'2.56 km',
    bigDetail:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
 
  },
  {
    name: 'Fish Food',
    quantity: 1,
    price: '$40',
    id:4,
    url : require('../assets/productImages/firstListImages/image2.jpg'),
    smallDetail: 'Lorem ipsum is simply dummy text.',
    age:2,
    sex:'female',
    color:'White',
    owner:'Jennifer Lorence',
    distance:'2.56 km',
    bigDetail:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
 
  },  {
    name: 'CatFood',
    quantity: 1,
    price: '$ 69',
    id:5,
    url : require('../assets/productImages/firstListImages/image2.jpg'),
    smallDetail: 'Lorem ipsum is simply dummy text.',
    age:2,
    sex:'female',
    color:'White',
    owner:'Jennifer Lorence',
    distance:'2.56 km',
    bigDetail:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
 
  },
  {
    name: 'DoberMan Pup',
    quantity: 1,
    price: '$40',
    id:6,
    url : require('../assets/productImages/firstListImages/image.3.jpg'),
    smallDetail: 'Lorem ipsum is simply dummy text.',
    age:2,
    sex:'female',
    color:'White',
    owner:'Jennifer Lorence',
    distance:'2.56 km',
    bigDetail:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
 
  },
  {
    name: 'Leash',
    quantity: 1,
    price: '$40',
    id:7,
    url : require('../assets/productImages/firstListImages/image1.webp'),
    smallDetail: 'Lorem ipsum is simply dummy text.',
    age:2,
    sex:'female',
    color:'White',
    owner:'Jennifer Lorence',
    distance:'2.56 km',
    bigDetail:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
 
  },
  {
    name: 'Fish Food',
    quantity: 1,
    price: '$40',
    id:8,
    url : require('../assets/productImages/firstListImages/image2.jpg'),
    smallDetail: 'Lorem ipsum is simply dummy text.',
    age:2,
    sex:'female',
    color:'White',
    owner:'Jennifer Lorence',
    distance:'2.56 km',
    bigDetail:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
 
  },
  {
    name: 'CatFood',
    quantity: 1,
    price: '$ 60',
    id:9,
    url : require('../assets/productImages/firstListImages/image2.jpg'),
    smallDetail: 'Lorem ipsum is simply dummy text.',
    age:2,
    sex:'female',
    color:'White',
    owner:'Jennifer Lorence',
    distance:'2.56 km',
    bigDetail:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
 
  },
  {
    name: 'DoberMan Pup',
    quantity: 1,
    price: '$40',
    id:10,
    url : require('../assets/productImages/firstListImages/image.3.jpg'),
    smallDetail: 'Lorem ipsum is simply dummy text.',
    age:2,
    sex:'female',
    color:'White',
    owner:'Jennifer Lorence',
    distance:'2.56 km',
    bigDetail:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
 
  },
  {
    name: 'Leash',
    quantity: 1,
    price: '$40',
    id:11,
    url : require('../assets/productImages/firstListImages/image1.webp'),
    smallDetail: 'Lorem ipsum is simply dummy text.',
    age:2,
    sex:'female',
    color:'White',
    owner:'Jennifer Lorence',
    distance:'2.56 km',
    bigDetail:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
 
  },
  {
    name: 'Fish Food',
    quantity: 1,
    price: '$40',
    id:12,
    url : require('../assets/productImages/firstListImages/image2.jpg'),
    smallDetail: 'Lorem ipsum is simply dummy text.',
    age:2,
    sex:'female',
    color:'White',
    owner:'Jennifer Lorence',
    distance:'2.56 km',
    bigDetail:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
 
  },
];
