export let VetList = [
  {
    name: 'Dr. ABC',
    specialist: 'Bone',
    address: 'New York',
    id: 1,
    url: require('../assets/Vet Images/doctor.jpg'),
  },
  {
    name: 'Dr. ABC',
    specialist: 'Bone',
    address: 'New York',
    id: 2,
    url: require('../assets/Vet Images/doctor.jpg'),
  },
  {
    name: 'Dr. ABC',
    specialist: 'Bone',
    address: 'New York',
    id: 3,
    url: require('../assets/Vet Images/doctor.jpg'),
  },
  {
    name: 'Dr. ABC',
    specialist: 'Bone',
    address: 'New York',
    id: 4,
    url: require('../assets/Vet Images/doctor.jpg'),
  },

  {
    name: 'Dr. ABC',
    specialist: 'Bone',
    address: 'New York',
    id: 5,
    url: require('../assets/Vet Images/doctor.jpg'),
  },
  {
    name: 'Dr. ABC',
    specialist: 'Bone',
    address: 'New York',
    id: 6,
    url: require('../assets/Vet Images/doctor.jpg'),
  },
  {
    name: 'Dr. ABC',
    specialist: 'Bone',
    address: 'New York',
    id: 7,
    url: require('../assets/Vet Images/doctor.jpg'),
  },
  {
    name: 'Dr. ABC',
    specialist: 'Bone',
    address: 'New York',
    id: 8,
    url: require('../assets/Vet Images/doctor.jpg'),
  },
  {
    name: 'Dr. ABC',
    specialist: 'Bone',
    address: 'New York',
    id: 9,
    url: require('../assets/Vet Images/doctor.jpg'),
  },
  {
    name: 'Dr. ABC',
    specialist: 'Bone',
    address: 'New York',
    id: 10,
    url: require('../assets/Vet Images/doctor.jpg'),
  },
  {
    name: 'Dr. ABC',
    specialist: 'Bone',
    address: 'New York',
    id: 11,
    url: require('../assets/Vet Images/doctor.jpg'),
  },
  {
    name: 'Dr. ABC',
    specialist: 'Bone',
    address: 'New York',
    id: 12,
    url: require('../assets/Vet Images/doctor.jpg'),
  },
];
